### ISSUE TITLE
List Strengths and Weaknesses

### ISSUE THREAD

**Issue by SBerkebile7** [SBerkebile7/Project-2-The-Cocktail-Menu#2]
Please leave a comment listing your strengths and weaknesses, we can also discuss this over Slack.

This will allow better placement within the project.

**Comment by SBerkebile7** [comment]
- Strengths
1. Back-end
2. JS

- Weaknesses
1. Front-end
2. Making things look nice :(

**Comment by ryanjolley12** [comment]
Strengths: 
1. Front end/CSS
2. Web/Third Party APIs
3. Workflow/Github

Weaknesses
1. SQL/Handlebars
2. JS

**Comment by 0xZ3n** [comment]
Strengths:
1. HTML/Basic (like, basic) CSS
2. JavaScript/JQuery/DOM Manipulation
3. Thinking through algorithms, refactoring logic
4. Feel basically competent in the Node stuff from Modules 9 and 10.

Areas of Opportunity:
1. SQL stuff, generally backend work

All that said, I'm willing to step out of my comfort zone, and improve my knowledge as we progress with the project, so long as there is the understanding that I make no claims at expertise.

**Comment by nelsondcds** [comment]
*Strengths
1. JavaScript
2. Web/Third Party APIs
3. HTML/CSS
*Weaknesses
1. Node
2. SQL
